name: Deploy Azure Function

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: upcoming-spotify # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Deploy Azure Functions"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  next-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: "Yarn Install"
        run: yarn install

      - name: "Next Build"
        run: yarn build

      - name: "Next Export"
        run: yarn export

      - name: Deploy Site to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: site/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
